name: bluesky_firehose
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

dependencies:
  bluesky: ^0.8.11

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
